#Convert input string to number
num = int(input("Enter a number: "))
print(num)
print(type(num))
num = float(input("Enter a number: "))
print(num)
print(type(num))
num = str(input("Enter a string: "))
print(num)
print(type(num))

# Convert variable type after input
num = input("Enter a number: ")
num = int(num)
print(num)
print(type(num))
num = input("Enter a number: ")
num = float(num)
print(num)
print(type(num))
num = input("Enter a string: ")
num = str(num)
print(num)
print(type(num))